language: node_js
node_js:
  - "stable"

branches:
  only:
  - master
  - dep-inclusions

cache:
  directories:
  - node_modules

install:
  - npm install -g yarn  
script:
  # - yarn lint
  # - yarn build
  - mv build/index.html build/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: a3ccc5dc17ae98d59fca7894b5ed0781791c7f6a
  local_dir: build
  on:
    branch: master
